eticaret/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include


from home import views
from order import views as orderviews
from home.views import file_upload_view

urlpatterns = [
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('product/', include('product.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('admin/', admin.site.urls), 
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('iletisim/', views.iletisim, name='iletisim'),      
    path('category/<int:id>/<slug:slug>/', views.category_products,name='category_products'),
    path('search/',views.product_search, name='product_search'),
    path('product/<int:id>/<slug:slug>/', views.product_detail,name='product_detail'),
    path('content/<int:id>/<slug:slug>/', views.content_detail,name='content_detail'),
    path('mail/', views.mail, name='mail'),

    path('search_auto/',views.product_search_auto, name='product_search_auto'),
    path('logout/',views.logout_view,name='logout_view' ),
    path('login/',views.login_view,name='login_view' ),
    path('signup/',views.signup_view,name='signup_view' ),
    path('shopcart/',orderviews.shopcart,name='shopcart'),

    path('upload/', file_upload_view, name='file_upload'),

    
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index, name ='index'), #atilsamancioglu.com/tweetapp/
    path('mail/', views.mail, name='mail'),
]

order/urls.py
from django.urls import path

from order import views


urlpatterns = [
    path('', views.index, name='index'),
    path('addtocart/<int:id>/', views.addtocart, name='addtocart'),
    path('deletefromcart/<int:id>/', views.deletefromcart, name='deletefromcart'),
    path('orderproduct/', views.orderproduct, name='orderproduct'),
    path('order/addtocart/<int:id>/', views.addtocart, name='addtocart'),

]

order/models.py
from django.contrib.auth.models import User
from django.db import models
# Create your models here.
from django.forms import ModelForm
from product.models import Product


class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()

    def __str__(self):
        return self.product.title
    
    @property
    def price(self):
        return (self.product.price)
    
    @property
    def amount(self):
        return (self.quantity * self.product.price)
    
class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']


class Order(models.Model): #checked
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preaparing', 'Preaparing'),
        ('OnShipping', 'OnShipping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, editable=False )#üye olmadan giriş yapan kişi için kod ile yapma
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    total = models.FloatField()
    status=models.CharField(max_length=10,choices=STATUS,default='New')
    ip = models.CharField(blank=True, max_length=20)
    adminnote = models.CharField(blank=True, max_length=100)
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name
    

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name','last_name','address','phone','city','country']

class OrderProduct(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.title

order/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from home.models import UserProfile
# Create your views here.
from order.models import ShopCartForm, ShopCart, OrderForm, Order, OrderProduct
from product.models import Category, Product
from django.utils.crypto import get_random_string


def index(request):
     return HttpResponse('Order App')

  
@login_required (login_url='/login') # Check Login  #checked
def addtocart (request, id):
    url= request.META.get('HTTP_REFERER') # get Last url
    current_user = request.user
    #******** ÜRÜRN SEPETTE VAR MI KONTROL****
    checkproduct = ShopCart.objects.filter(product_id=id) #varmı kontrol
    if checkproduct:
         control = 1
    else:
         control = 0
    
    if request.method == 'POST': # form post edildiyse ürün detay sayasından
        form = ShopCartForm (request. POST)
        if form.is_valid ():
            if control ==1:
                data = ShopCart.objects.get(product_id=id)
                data.quantity += form.cleaned_data['quantity']
                data.save()  #
            else:  #  ürün yoksa ekle
                data = ShopCart()  # model ile bağlantı kur
                data.user_id = current_user.id
                data.product_id = id
                data.quantity = form.cleaned_data['quantity']
                data.save()  #
        request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count() #count item on shopcart
        messages.success(request, "ürün sepete eklendi")
        return HttpResponseRedirect(url)
                    #return HttpResponse ("Kaydedildi")
    else: #ürün sepete ekle butonuna basıldıysa
        if control ==1: #ürün varsa güncelle
            data = ShopCart.objects.get(product_id=id)
            data.quantity += 1
            data.save()  #
        else:  #  ürün yoksa ekle
            data = ShopCart() #model ile bağlantı4
            data.user_id = current_user.id
            data.product_id = id  
            data.quantity = 1
            data.save() #veritabanına kaydet
        request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count() 
        messages.success(request, "ürün sepete eklendi.")
        return HttpResponseRedirect(url) 
    
    messages.warning(request, "ürün eklenirken hata oluştu. kontrol edin")
    return HttpResponseRedirect(url)



@login_required(login_url='/login') #check again  #checked bat request session fazla 
def shopcart(request):
    category = Category.objects.all()   #checked
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count()

    total = 0
    for rs in shopcart:
        total += rs.product.price * rs.quantity

    context = { 'shopcart':shopcart,
               'total':total,
               'category':category
               }    
    return render(request,'shopcart_product.html',context)

@login_required(login_url='/login')  #checked
def deletefromcart(request,id):
     ShopCart.objects.filter(id=id).delete()
     current_user = request.user
     request.session['cart_items'] = ShopCart.objects.filter(user_id=current_user.id).count
     messages.success(request,"ürün silindi")
     return HttpResponseRedirect("/shopcart")


@login_required(login_url='/login')  #checked
def orderproduct(request):
    category = Category.objects.all()
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    total = 0
    for rs in shopcart:       
        total += rs.product.price * rs.quantity
          
    if request.method == 'POST':  # if there is a post
        form = OrderForm(request.POST)
        #return HttpResponse(request.POST.items())
        if form.is_valid():
            # Send Credit card to bank,  If the bank responds ok, continue, if not, show the error
            # ..............
            data = Order()
            data.first_name = form.cleaned_data['first_name'] #get product quantity from form
            data.last_name = form.cleaned_data['last_name']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.user_id = current_user.id
            data.total = total
            data.ip = request.META.get('REMOTE_ADDR')
            ordercode= get_random_string(5).upper() # random cod
            data.code =  ordercode
            data.save() #
            #sepetteki ürünleri ordera kaydetme
            shopcart = ShopCart.objects.filter(user_id=current_user.id)
            for rs in shopcart:
                detail = OrderProduct()
                detail.order_id    = data.id # Order için oluşturulan id orders producta kaydediliyo
                detail.product_id  = rs.product_id
                detail.user_id     = current_user.id
                detail.quantity    = rs.quantity   
                detail.price = rs.product.price
                detail.amount = rs.amount
                detail.save()
             
                # ***Reduce quantity of sold product from Amount of Product
                product = Product.objects.get(id=rs.product_id)
                product.amount -= rs.quantity #sepete eklenen ürün kadar productan düşürülüyor mevcut kalan belirlensin
                product.save()
                
            ShopCart.objects.filter(user_id=current_user.id).delete() # Clear & Delete shopcart
            request.session['cart_items']=0
            messages.success(request, "Your Order has been completed. Thank you ")
            return render(request, 'Order_Completed.html',{'ordercode':ordercode,'category':category,})
        else:
            messages.warning(request, form.errors)
            return HttpResponseRedirect("/order/orderproduct")

    form= OrderForm()
    profile = UserProfile.objects.get(user_id=current_user.id)
    context = {'shopcart': shopcart,
               'category': category,
               'total': total,
               'form': form,
               'profile': profile,
               }
    return render(request, 'Order_Form.html', context)


        

  

order/templates/Order_Form.html
{% extends "homebase.html" %}

{% block title %}   Shop Cart {% endblock %}
{% block keywords %} {{ categorydata.keywords }} {% endblock %}
{% block description %} {{ categorydata.description }} {% endblock %}

{% block head %}
    <link rel="shortcut icon" type="image/x-icon" href="{{setting.icon.url}}" />
{% endblock %}


{% block sidebar %} {% include 'sidebar.html' %}  {% endblock %}   

{% block content %}


<!-- BREADCRUMB -->
<div id="breadcrumb">
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="/">Home</a></li>
            <li class="active">Order Page</li>
        </ul>
    </div>
</div>
<!-- /BREADCRUMB -->
<!-- section -->
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div  class="row">
            <Form action="" method="post">
                {% csrf_token %}
                <div class="col-md-6">
                    <div class="billing-details">

                        <div class="section-title">
                            <h4 class="title">Shipping Details</h4>
                        </div>
                        <p><label for="id_first_name">First name:</label>
                            <input type="text" name="first_name"  value="{{ user.first_name }}" class="input" maxlength="10" required id="id_first_name"></p>
                        <p><label for="id_last_name">Last name:</label>
                            <input type="text" name="last_name"  value="{{ user.last_name }}" class="input" maxlength="10" required id="id_last_name"></p>
                        <p><label for="id_address">Address:</label>
                            <input type="text" name="address" value="{{ profile.address }}" class="input" maxlength="150" id="id_address"></p>
                        <p><label for="id_phone">Phone:</label>
                            <input type="text" name="phone"  value="{{ profile.phone }}"  class="input" maxlength="20" id="id_phone"></p>
                        <p><label for="id_city">City:</label>
                            <select name="city" class="input" id="id_city">
                                <option value="{{ profile.city }}" selected>{{ profile.city }}</option>
                                <option value="İstanbul">Istanbul</option>
                                <option value="Ankara">Ankara</option>
                                <option value="İzmir">Izmir</option>
                                <option value="Bursa">Bursa</option>
                                <option value="Konya">Konya</option>
                                <option value="Yozgat">Yozgat</option>
                            </select></p>
                        <p><label for="id_first_name">Country :</label>
                            <input type="text" name="country" class="input" id="id_country" value="{{ profile.country }}"></p>
                        <div class="pull-right">
                            <button  type="submit" class="primary-btn">Complete Order</button>
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="shiping-methods">
                        <div class="section-title">
                            <h4 class="title">Payment Information</h4>
                        </div>
                        <p><label for="id_first_name">Total: </label> 
                            <input type="text" name="total" class="input" readonly value="${{ total }}"></p> 
                        <p><label for="id_first_name">Credit Card Holder</label>
                            <input type="text" name="holder" class="input"  value=""></p>
                        <p><label for="id_first_name">Credit Card Number</label>
                            <input type="text" name="number" class="input"  value=""></p>
                        <p><label for="id_first_name">Credit Exp Date/Year</label>
                            <input type="text" name="ecpdate" class="input"  placeholder="mm/yy"></p>
                        <p><label for="id_first_name">Security Number</label>
                            <input type="text" name="secnumber" class="input"  value=""></p>
                    </div>
                </div>

            </Form>


            <div class="col-md-12">
                <div class="order-summary clearfix">
                    <div class="section-title">
                        <h3 class="title">Shopcart Product List</h3>
                    </div>
                    <table class="shopping-cart-table table">
                        <thead>
                        <tr>
                            <th></th>
                            <th>Product</th>
                            <th class="text-center">Price</th>
                            <th class="text-center">Quantity</th>
                            <th class="text-center">Total</th>
                            <th class="text-right"></th>
                        </tr>
                        </thead>
                        <tbody>

                        {% for rs in shopcart %}
                            <tr>
                                <td class="thumb">  <img src="{{rs.product.image.url}}" alt=""></td>
                                <td class="details">
                                    <a href="/product/{{ rs.product.id }}/{{ rs.product.slug }}">{{rs.product}} {{ rs.variant.size }} {{ rs.variant.color }}</a>  </td>
                                <td class="price text-center"><strong>
                                    {% if rs.product.variant == 'None' %}
                                        {{ rs.product.price|currency:request.session.currency }} {{ request.session.currency }}
                                    {% else %}
                                        {{ rs.variant.price|currency:request.session.currency }} {{ request.session.currency }}
                                    {% endif %}
                                </strong></td>
                                <td class="qty text-center"><strong>{{rs.quantity}}</strong></td>
                                <td class="total text-center"><strong class="primary-color">$
                                    {% if rs.product.variant == 'None' %}
                                        {{ rs.amount|currency:request.session.currency }} {{ request.session.currency }}
                                    {% else %}
                                        {{ rs.varamount|currency:request.session.currency }} {{ request.session.currency }}
                                    {% endif %}
                                </strong></td>
                                <td class="text-right"><a href="/order/deletefromcart/{{ rs.id }}" onclick="return confirm('Delete ! Are you sure?')" class="main-btn icon-btn"><i class="fa fa-close"></i></a></td>
                            </tr>

                        {% endfor %}

                        </tbody>
                        <tfoot>
                        <tr>
                            <th class="empty" colspan="3"></th>
                            <th>SUBTOTAL</th>
                            <th colspan="2" class="sub-total">{{ total|currency:request.session.currency }} {{ request.session.currency }}</th>
                        </tr>
                        <tr>
                            <th class="empty" colspan="3"></th>
                            <th>SHIPING</th>
                            <td colspan="2">Free Shipping</td>
                        </tr>
                        <tr>
                            <th class="empty" colspan="3"></th>
                            <th>TOTAL</th>
                            <th colspan="2" class="total">{{ total|currency:request.session.currency }} {{ request.session.currency }}</th>
                        </tr>
                        </tfoot>
                    </table>

                </div>

            </div>

        </div>    





        </div>
    </div>
{% endblock %}      

order/templates/shopcart_product.html
            {% extends "homebase.html" %}

            {% block title %}   Shop Cart {% endblock %}
            {% block keywords %} {{ categorydata.keywords }} {% endblock %}
            {% block description %} {{ categorydata.description }} {% endblock %}

            {% block head %}
                <link rel="shortcut icon" type="image/x-icon" href="{{setting.icon.url}}" />
            {% endblock %}


            {% block sidebar %} {% include 'sidebar.html' %}  {% endblock %}   

            {% block content %}


            <!-- BREADCRUMB -->
            <div id="breadcrumb">
                <div class="container">
                    <ul class="breadcrumb">
                            <li><a href="/">Anasayfa</a></li>
                            <li class="active">{{ categorydata.title}}</li>
                    </ul>
                </div>
            </div>
            <!-- /BREADCRUMB -->

 
            <div class="section">
                <!-- container -->
                <div class="container">
                    <!-- row -->
                    <div class="row">

                        <div class="col-md-12">
                            <div class="order-summary clearfix">
                                  <div class="section-title">
                                      <h3 class="title">Shopcart Product List </h3>
                                  </div>
                                  <table class="shopping-cart-table table">
                                        <thead>
                                            <tr>
                                                <th>Product</th>
                                                <th></th>
                                                <th class="text-center">Price</th>
                                                <th class="text-center">Quantity</th>
                                                <th class="text-center">Total</th>
                                                <th class="text-right"></th>
                                            </tr>
                                        </thead>
                                        <tbody>


                                        {% for rs in shopcart %}
                                            <tr>
                                                <td class="thumb"><img src="{{rs.product.image.url}}" alt=""></td>
                                                <td class="details"><a href="#">{{ rs.product}}</a>
                                                    <ul>
                                                        <li><span>Size: XL</span></li>
                                                        <li><span>Color: XL</span></li>
                                                    </ul>
                                                </td>
                                                <td class="price text-center"><strong>${{rs.product.price}}</strong></td>
                                                <td class="qty text-center"><strong>{{rs.quantity}}</strong></td>   
                                                <td class="total text-center"><strong class="primary-color">${{rs.amount}}</strong></td>
                                                <td class="text-right">
                                                    <a href="/order/deletefromcart/{{ rs.id }}" onclick="return confirm('Delete ! Are you sure?')" class="main-btn icon-btn">
                                                        <i class="fa fa-close"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        {% endfor %}        

                         
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <th class="empty" colspan="3"></th>
                                            <th>SUBTOTAL</th>
                                            <th colspan="2" class="sub-total">${{ total }}</th>
                                        </tr>
                                        <tr>
                                            <th class="empty" colspan="3"></th>
                                            <th>SHIPING</th>
                                            <td colspan="2">Free Shipping</td>
                                        </tr>
                                        <tr>
                                            <th class="empty" colspan="3"></th>
                                            <th>TOTAL</th>
                                            <th colspan="2" class="total">${{ total }}</th>
                                    </tr>
                                    </tfoot>
                                </table>    
                                <div class="pull-right"></div>
                                    <a href="/order/orderproduct" class="primary-btn">Place Order</a>
                                </div>
                            </div>    
                        

                        </div>
                    </div>
                </div>
                </div>
            {% endblock %}